import fs from 'node:fs';
import { envPath } from '../lib/paths.js';
import { loadEnvFile } from '../lib/env.js';

const OPTIONAL_KEYS = ['CIVITAI_TOKEN', 'HF_TOKEN', 'HUGGING_FACE_HUB_TOKEN', 'COMFY_PREVIEW_METHOD'];

/**
 * @param {Record<string, string | undefined | null>} vars
 */
export function writeEnvFile(vars) {
  const existing = loadEnvFile();
  const mode = vars.COMFY_MODE || existing.COMFY_MODE || 'local';
  const lines = [
    '# Generated by Darkroom setup wizard. Edit as needed.',
    '',
    `PORT=${vars.PORT || existing.PORT || '3001'}`,
    `COMFY_URL=${vars.COMFY_URL || existing.COMFY_URL || 'http://127.0.0.1:8188'}`,
    `COMFY_MODE=${mode}`,
  ];

  if (mode !== 'remote') {
    const dir = vars.COMFY_DIR || existing.COMFY_DIR;
    const python = vars.COMFY_PYTHON || existing.COMFY_PYTHON;
    if (dir) lines.push(`COMFY_DIR=${dir}`);
    if (python) lines.push(`COMFY_PYTHON=${python}`);
  }

  lines.push('', '# Optional');
  let wroteOptional = false;
  for (const key of OPTIONAL_KEYS) {
    const val = vars[key] ?? existing[key];
    if (val) {
      lines.push(`${key}=${val}`);
      wroteOptional = true;
    }
  }
  if (!wroteOptional) {
    lines.push('# CIVITAI_TOKEN=', '# HF_TOKEN=', '# COMFY_PREVIEW_METHOD=auto');
  }
  lines.push('');

  fs.writeFileSync(envPath, lines.join('\n'), 'utf8');
  return envPath;
}
