import fs from 'node:fs';
import { envPath } from '../lib/paths.js';

/**
 * @param {Record<string, string | undefined | null>} vars
 */
export function writeEnvFile(vars) {
  const lines = [
    '# Generated by Darkroom setup wizard. Edit as needed.',
    '',
    `PORT=${vars.PORT || '3001'}`,
    `COMFY_URL=${vars.COMFY_URL || 'http://127.0.0.1:8188'}`,
    `COMFY_MODE=${vars.COMFY_MODE || 'local'}`,
  ];

  if (vars.COMFY_MODE !== 'remote') {
    if (vars.COMFY_DIR) lines.push(`COMFY_DIR=${vars.COMFY_DIR}`);
    if (vars.COMFY_PYTHON) lines.push(`COMFY_PYTHON=${vars.COMFY_PYTHON}`);
  }

  lines.push(
    '',
    '# Optional',
    '# CIVITAI_TOKEN=',
    '# HF_TOKEN=',
    '# COMFY_PREVIEW_METHOD=auto',
    '',
  );

  fs.writeFileSync(envPath, lines.join('\n'), 'utf8');
  return envPath;
}
